src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Entity\Image;
use App\Service\Slug;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\TrickRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=TrickRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields={"name"},
 * message = "Le nom de cette figure déjà utilisé, veuillez taper une autre nom de figure !")
 */
class Trick
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="tricks", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="tricks", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank
     * @Assert\Length(
     * min=5,
     * max=35, 
     * minMessage="Merci de rentrer plus de 5 caractères pour le nom de la figure.", 
     * maxMessage="Merci de ne pas entrer plus de 35 caractères pour le nom de la figure."
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=70)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     * @Assert\Length(
     * min=5,
     * minMessage="Merci de rentrer plus de 5 caractères pour le descriptif."
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $update_date;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="trick", cascade ={"persist"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=Video::class, mappedBy="trick", cascade ={"persist"}, orphanRemoval=true)
     * @Assert\Valid()
     */
    private $videos;

     /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="trick", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=TrickLike::class, mappedBy="trick", cascade ={"persist"}, orphanRemoval=true)
     */
    private $likes;


    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        $this->setSlug($this->name);

        return $this;
    }

    /**
     * slug initialize
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug()
    {
        if(empty($this->slug)) {
            $slugify = new Slug();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }
    
    public function setSlug($slug): self
    {
        $slugify = new Slug();
        $this->slug = $slugify->slugify($slug);

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getUpdateDate(): ?\DateTimeInterface
    {
        return $this->update_date;
    }

    public function setUpdateDate(\DateTimeInterface $update_date): self
    {
        $this->update_date = $update_date;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TrickLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(TrickLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setTrick($this);
        }

        return $this;
    }

    public function removeLike(TrickLike $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getTrick() === $this) {
                $like->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * like or not by user
     *
     * @param User $user
     * @return boolean
     */
    public function isLikedByUser(User $user) : bool
    {
        foreach ($this->likes as $like) {
            if($like->getUser() === $user) return true;
        }
        return false;
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Trick;
use App\Entity\Comment;
use App\Form\TrickType;
use App\Entity\TrickLike;
use App\Form\CommentType;
use App\Service\Paginator;
use App\Service\FileUploader;
use App\Security\Voter\TrickVoter;
use App\Repository\TrickRepository;
use App\Repository\CategoryRepository;
use App\Repository\TrickLikeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/trick")
 */
class TrickController extends AbstractController
{
    /**
     * $manager construct
     *
     * @var EntityManagerInterface
     */
    private $manager;

    public function __construct(EntityManagerInterface $manager)
    {
        $this->manager = $manager;
    }

    /**
     * @Route("/", name="trick_index", methods={"GET"})
     */
    public function index(TrickRepository $trickRepository): Response
    {
        return $this->render('trick/index.html.twig', [
            'tricks' => $trickRepository->findAllTricks()
            ]);
    }

    /**
     * @Route("/{slug}", name="trick_category", priority=-1)
     */
    public function category($slug, CategoryRepository $repo): Response
    {
        $category = $repo->findOneBy([
            'slug' => $slug
        ]);

        if(!$category){
            throw $this->createNotFoundException("Cette catégorie n'existe pas !");
        }

        return $this->render('trick/category.html.twig', [
            'slug' => $slug,
            'category' => $category
        ]);
    }

    /**
     * @Route("/{slug}/show/{page<\d+>?1}", name="trick_show", methods={"GET","POST"})
     */
    public function show(Request $request, Trick $trick, Paginator $paginator, $page): Response
    {
        $form = $this->createForm(CommentType::class);
        $form->handleRequest($request);
        $paginator
            ->setEntityClass(Comment::class)
            ->setOrder(['creation_date' => 'DESC'])
            ->setPage($page)
            ->setAttribut(['trick' => $trick]);
        return $this->render('trick/show.html.twig', [
            'slug' => $trick->getSlug(),
            'trick' => $trick,
            'paginator' => $paginator,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/new", name="trick_new", methods={"GET","POST"})
     * @param $fileUploader
     */
    public function new(Request $request, FileUploader $fileUploader): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $trick = new Trick();
        $trick->setUser($this->getUser());
        $trick->getSlug('name');
        $trick->setCreationDate(new \Datetime());

        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $uploadedFile */
            $images = $form['images']->getData();

            foreach ($images as $image) {
                $uploadedFile = $image->getFile();
                if ($uploadedFile) {
                    $newFilename = $fileUploader->upload($uploadedFile, 'images');
                    $image->setPath($newFilename);
                }
                $image->setTrick($trick);
                $this->manager->persist($image);
            }

            foreach ($trick->getVideos() as $video) {
                $video->setTrick($trick);
                $this->manager->persist($video);
            }
            $this->manager->persist($trick);
            $this->manager->flush();
            $this->addFlash('message', 'Trick added!');
            return $this->redirectToRoute('trick_index');
        }

        return $this->render('trick/new.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/trick/{slug}/edit", name="trick_edit")
     *
     */
    public function edit(Request $request, Trick $trick, FileUploader $fileUploader): Response
    {
        $this->denyAccessUnlessGranted(TrickVoter::EDIT, $trick);
        $trick->setUpdateDate(new \Datetime());

        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $images = $form['images']->getData();

            foreach ($images as $image) {
                $uploadedFile = $image->getFile();
                if ($uploadedFile) {
                    $newFilename = $fileUploader->upload($uploadedFile, 'images');
                    $image->setPath($newFilename);
                } 
        
                $image->setTrick($trick);
                $this->manager->persist($image);
                
            }

            $videos = $form['videos']->getData();
            foreach ($videos as $video) {
                $video->setTrick($trick);
                $this->manager->persist($video);
            }

            $this->manager->persist($trick);
            $this->manager->flush();
            $this->addFlash('message', 'Trick modified!');
            return $this->redirectToRoute('trick_show', [
                'slug' => $trick->getSlug()
            ]);
        }
        return $this->render('trick/edit.html.twig', [
            'trick' => $trick,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}/newcomment/{page<\d+>?1}", name="comment_new", methods={"GET","POST"})
     */
    public function newComment(Request $request, Trick $trick, EntityManagerInterface $manager, Paginator $paginator, $page): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $comment = new Comment();
        $comment->setUser($this->getUser());
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setCreationDate(new \DateTime())
                ->setTrick($trick);

            $manager->persist($comment);
            $manager->flush();
            $this->addFlash('message', 'Comment added!');
            return $this->redirectToRoute('trick_show', [
                'id' => $trick->getId(),
                'slug' => $trick->getSlug(),
            ]);
        }
        $paginator
            ->setEntityClass(Comment::class)
            ->setOrder(['creation_date' => 'DESC'])
            ->setPage($page)
            ->setAttribut(['trick' => $trick]);



        return $this->render('trick/show.html.twig', [
            'trick' => $trick,
            'slug' => $trick->getSlug(),
            'paginator' => $paginator,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/delete", name="trick_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Trick $trick): Response
    {
        $filesystem = new Filesystem();
        $this->denyAccessUnlessGranted('ROLE_USER');
        if ($this->isCsrfTokenValid('delete' . $trick->getId(), $request->request->get('_token'))) {
            foreach ($trick->getImages() as $image) {
                $filesystem->remove('assets/uploads/images/' . $image->getPath());
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($trick);
            $entityManager->flush();
            $this->addFlash('message', 'trick deleted!');
        }

        return $this->redirectToRoute('trick_index');
    }

    /**
     * add and supp likes
     * 
     * @Route("/{slug}/like", name="trick_like")
     *
     * @param Trick $trick
     * @param EntityManagerInterface $manager
     * @param TrickLikeRepository $trickLikeRepository
     * @return void
     */
    public function like(Trick $trick, EntityManagerInterface $manager, TrickLikeRepository $trickLikeRepository)
    {
        $user = $this->getUser();
        
        if(!$user) return $this->json([
            'code' => 403,
            'Message' => "please get connect !"
        ], 403);

        if($trick->isLikedByUser($user)) {
            $like = $trickLikeRepository->findOneBy([
                'trick' => $trick,
                'user' => $user
            ]);

            $manager->remove($like);
            $manager->flush();

            return $this->json([
                'code' => 200,
                'Message' => "like delete !",
                'likes' => $trickLikeRepository->count(['trick' => $trick])
            ], 200);

        }

        $like = new TrickLike();
        $like->setTrick($trick)
        ->setUser($user);
        
        $manager->persist($like);
        $manager->flush();

        return $this->json([
            'code' => 200,
            'Message' => "like added !",
            'likes' => $trickLikeRepository->count(['trick' => $trick])
        ], 200);
    }  
}

templates/trick/_delete_form.html.twig
<form method="post" action="{{ path('trick_delete', {'id': trick.id}) }}" onsubmit="return confirm('Are you sure you want to delete this trick?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id) }}">
    {% if is_granted('edit', trick) %}
    <button class="btn-roun-shadow d-flex d-inline-block btn-delete-image btn btn-danger fas fa-trash-alt"></button>
    {% endif %}
</form>

templates/trick/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
{% if app.request.attributes.get('_route') == 'trick_edit' %}
{% endif %}
<button class="btn-roun-shadow btn btn-success">{{ button_label|default('Add trick !') }}</button>
{{ form_end(form) }}

templates/trick/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégorie : {{ category.slug }} {% endblock %}

{% block body %}
{{ include('home/_home.html.twig') }}
<div class="margout row">
    <div class="col-12 mb-4"><br><br>
        <h1 class="title text-center">Catégorie : {{category.slug }}</h1><br><br>
    </div>
    {% for trick in category.tricks %}
    <div class="col-lg-2 col-sm-12 col-md-6 my-3 m-4  ">
        <div class="card shadow">
            <a href="{{ path('comment_new', {'slug': trick.slug}) }}">
                <div class="col-12 p-2">
                    <div class="mw-100 overflow-hidden">
                        {% if trick is not empty %}
                        {% for image in trick.images %}
                        {% if loop.first %}
                        <img class="h-100 w-100" src="{{ asset('assets/uploads/images/' ~ image.path) }}"
                            alt="{{ trick.name }}">
                        {% endif %}
                        {% else %}
                        <img class="h-100 w-100" src="{{ asset('assets/img_default/460.jpg') }}" alt="logoSnow">
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="d-flex col-12 p-3 name-trick">
                        <div class="d-flex text-align-inline">{{ trick.name }}
                            {% if is_granted('edit', trick) %}
                            <a class="px-2" href="{{ path('trick_edit', {'slug': trick.slug}) }}"><i
                                    class="fas fa-pen "></i></a>
                            {{ include('trick/_delete_form.html.twig') }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/trick/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% for message in app.flashes('message') %}
<div class="alert alert-success text-center" role="alert">
    {{ message }}
</div>
{% endfor %}
<div>
    {% include 'trick/trickslisttricks.html.twig' %}
</div><br>
{% if app.user %}
<div class= "d-flex justify-content-center">

<a class="btn-roun-shadow btn-rounded btn btn-secondary text-white nav-link shadow" href="{{ path('trick_new') }}">Create new Trick !</a>
</div><br><br><br>
{% endif %}
{% endblock %}

templates/trick/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}New Trick{% endblock %}
{% form_theme form _self %}
{% block body %}
<div class="container text-center"><br>
	<h1>Create new Trick</h1>
	<section class="add-trick my-4">
		{{ include('trick/_form.html.twig') }}
	</section>
	<a href="{{ path('trick_index') }}" class="btn-roun-shadow btn btn-secondary">back to list</a>
</div>
{% endblock %}
{% block form_row %}
<div class="form-group my-4">
	{#{{dump()}}#}
	{{ form_label(form) }}
	{{ form_widget(form) }}
</div>
{% endblock %}
{% block _trick_images_row %}
<h3>Add pictures</h3>
{{ form_widget(form) }}
<div class=>
	<button type="button" class="btn-roun-shadow btn btn-primary btn-add-images my-4" id="add-images">Add Picture</button>
</div>
{% endblock %}
{% block _trick_images_entry_widget %}
<div id="block_{{id}}">
	{{ form_widget(form.file)}}
	<button type="button" data-action="delete" data-target="#block_{{id}}"
		class="btn btn-danger fas fa-trash-alt"></button>
</div>

{% endblock %}
{% block _trick_videos_row %}
<h3>Add videos</h3>
{{ form_widget(form) }}
<button type="button" class="btn-roun-shadow btn btn-primary btn-add-videos my-4" id="add_videos">Add video</button><br><br>
{% endblock %}
{% block _trick_videos_entry_widget %}
<div id="block_{{id}}">
	<div class="row">
		<div class="col-10">
			<div class="row">
				<div class="col">
					{{ form_widget(form.url) }}
				</div>
				<div class="col">
					{{ form_widget(form.name) }}
				</div>
			</div>
		</div>
		<div class="col-2">
			<button type="button" data-action="delete" data-target="#block_{{id}}"
				class="btn btn-danger fas fa-trash-alt"></button>
		</div>
	</div>
</div>
{% endblock %}
{% block javascripts %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
	integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
	crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
	integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
	crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
	integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
	crossorigin="anonymous"></script>
<script src="{{ asset('assets/js/handleForm.js') }}"></script>
<script src="{{ asset('assets/js/addFileName.js') }}"></script>
{% endblock %}

templates/trick/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Trick{% endblock %}
{% block body %}
{% for message in app.flashes('message') %}
<div class="alert alert-success text-center" role="alert">
    {{ message }}
</div>
{% endfor %}
<div class="container text-center border mt-4">
    <h2 class="title-show mt-2">{{ trick.name }}</h2>
    {% if trick is not empty %}
    {% for image in trick.images %}
    {% if loop.first %}
    <div class="edit-image-poster mt-4">
        <img class="image-trick image-trick-poster rounded mb-2" src="{{ asset('assets/uploads/images/' ~ image.path) }}" alt="Image"
        height="100" width="150">
        {% if is_granted('edit', trick) %}
        <div class="bt-edit-poster d-flex">
            {{ include('trick/_delete_form.html.twig') }}
            <a href="{{ path('trick_edit', {'slug': trick.slug}) }}"
            class="d-flex d-inline-block ml-1 btn btn-primary fas fa-pencil-alt"></a>
        </div>
        {% endif %}
    </div>
    {% endif %}
    {% else %}
    <div class="image-poster mt-4">
        <img class="image-trick image-trick-poster rounded mx-2" src="{{ asset('assets/img_default/460.jpg') }}" alt="Image" height="100"
        width="100">
        {% if is_granted('edit', trick) %}
        <div class="bt-edit-poster d-flex">
            {{ include('trick/_delete_form.html.twig') }}
            <a href="{{ path('trick_edit', {'slug': trick.slug}) }}"
            class="d-flex d-inline-block ml-1 btn btn-primary fas fa-pencil-alt"></a>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    {% endif %}
    <div class="media-none align-items-center text-align-inline justify-content-center my-4">
        {% for image in trick.images %}
        {% if not loop.first %}
        <img class="image-trick-mini rounded mx-2 mb-2" src="{{ asset('assets/uploads/images/' ~ image.path) }}" alt="Image"
        height="100" width="150">
        {% endif %}
        {% endfor %}
        <div class="container">
            <div class="row justify-content-center">
                {% for video in trick.videos %}
                <div class="d-flex text-align-inline align-items-center justify-content-center my-4">
                    <iframe class="video-trick-mini video-tricks mb-1 mr-4 rounded  {{ trick.id }}" src="{{ video.url }}" frameborder="0"
                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <input type="button" class="see btn-roun-shadow btn btn-success mt-2 mb-2" value="See Medias">
    <div class="align-items-center">
        <h3>Description :</h3>
        <div class="d-flex justify-content-center">
            <p class="text-muted  text-justify">{{ trick.description }}</p>
        </div>
        <div class=" align-items-center d-flex text-align-inline justify-content-center  my-4">
            <div class="border mx-2 px-2 rounded">
                <h6>Groupe :</h6>
                <p class="text-muted">{{ trick.category.category }}</p>
            </div>
            <div class="border mx-2 px-2 rounded">
                <h6>Publié le :</h6>
                <p class="text-muted">{{ trick.creationDate ? trick.creationDate|date('d/m/Y') : '' }} par
                    {{ trick.user.pseudo }}</p>
                </div>
                {% if trick.updateDate %}
                <div class="border mx-2 px-2 rounded ">
                    <h6>Modifié le :</h6>
                    <p class="text-muted">{{ trick.updateDate ? trick.updateDate|date('d/m/Y') : '' }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <hr>
    {% if app.user %}
    <div class="align-items-center d-flex text-align-inline justify-content-center  my-4">
        {{ form_start(form, { "attr": { "class": "text-center"} }) }}
        {{ form_row(form.content)}}
        <button type="submit" class="btn-roun-shadow btn btn-success">leave a comment</button>
        {{ form_end(form) }}
    </div>
    {% else %}
    <h2 class="text-center">Pour laisser un commentaire veuillez vous connecter</h2>
    {% endif %}
    <hr>
    <h3 class="text-center my-4">{{ trick.comments|length}} Commentaires pour l'article : {{ trick.name }}</h3>
    {% for comment in paginator.data %}
    {% if comment.user.avatar %}
    <div class="container">
        <div class="comment-avatar d-flex align-items-inline justify-content-center">
            <img class="profile mx-2" src="{{ asset('assets/avatars/img_profile/' ~ comment.user.avatar) }}" alt="Image"
            height="100" width="100">
            {% else %}
            <div class="comment-avatar d-flex align-items-inline justify-content-center">
                <img class="profile mx-2" src="{{ asset('assets/avatars/default.jpg') }}" alt="Image" height="100"
                width="100">
                {% endif %}
                <div class="comment-content mt-2 mb-4 border">
                    <p class="mx-4">Pulié par : {{ comment.user.pseudo }} Le :
                        {{ comment.creationDate ? comment.creationDate|date('d/m/Y') : '' }}</p>
                        <p>{{ comment.content }}</p>
                    </div>
                </div>
            </div>
            {% else %}
            <p class="text-center text-success">Soyez le premier à laisser un commentaire...</p>
            {% endfor %}
        </div>
        {% if paginator.data is not empty %}
        <div class="d-flex justify-content-center pagination-sm">
            {% set page = paginator.page %}
            {% set pages = paginator.pages %}
            <ul class="pagination">
                <li class="page-item {% if page == 1 %}disabled{% endif %}">
                    <a class="page-link" href="{{ path('trick_show', {'slug': trick.slug, 'page': page - 1}) }}">Previous</a>
                </li>
                {% for i in 1..pages %}
                <li class="page-item {% if page == i %}active{% endif %}">
                    <a class="page-link" href="{{ path('trick_show', {'slug': trick.slug, 'page': i}) }}">{{ i }}</a>
                </li>
                {% endfor %}
                <li class="page-item {% if page == pages %}disabled{% endif %}">
                    <a class="page-link" href="{{ path('trick_show', {'slug': trick.slug, 'page': page + 1}) }}">Next</a>
                </li>
            </ul>
        </div>
        {% endif %}
        <div class="text-center">
            <a href="{{ path('homepage') }}" class="btn-roun-shadow btn btn-secondary">back to list</a>
        </div>
        
        {% endblock %}
        {% block javascripts %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
        <script src="{{ asset('assets/js/pics.js') }}"></script>
        <script src="{{ asset('assets/js/loadMoreTricks.js') }}"></script>
        {% endblock %}